services:
  - type: web
    name: ia-tributaria-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python simple_server.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 8001
      - key: HOST
        value: 0.0.0.0
    healthCheckPath: /health